project:
  type: website

website:
  title: "Jules Walzer-Goldfeld"
  site-url: https://juleswg23.github.io/
  navbar:
    right:
      - file: index.qmd
        text: "about"
      - file: blog.qmd
        text: "blog"
      - file: work.qmd
        text: "work"
      - icon: github
        href: https://github.com/juleswg23
      - icon: linkedin
        href: https://www.linkedin.com/in/jules-w-51bb03199/
      # - icon: rss
      #   href: blog.xml

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



