project:
  type: website

website:
  title: "Jules Walzer-Goldfeld"
  site-url: https://juleswg.me/
  favicon: images/logo.svg
  navbar:
    right:
      - file: index.qmd
        text: "about"
      - file: blog.qmd
        text: "blog"
      - file: work.qmd
        text: "work"
      - icon: github
        href: https://github.com/juleswg23
      - icon: linkedin
        href: https://www.linkedin.com/in/jules-w-51bb03199/
      - icon: rss
        href: blog.xml
    logo: images/logo.png

format:
  html:
    canonical-url: true
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: 
      text: |
        <link rel="shortcut icon" href="images/logo.svg" />
        <link rel="icon" type="image/x-icon" href="images/logo.ico">

