---
title: "Things I've Done"
---

## Open Source

**gt-extras**

* Author of the [gt-extras](https://posit-dev.github.io/gt-extras/) library, a collection of helpers for Great Tables
* Based on {gtExtras} in R

**Great Tables**

* Contributor to a number of features and bug fixes in [the popular port of R's {gt}](https://github.com/posit-dev/great-tables)
* Published an entry in the [Great Tables blog](https://posit-dev.github.io/great-tables/blog/plots-in-tables/)

## Talks

[Slides](./talks/Posit-Open-Source-Reflection/index.qmd) for a talk I gave about my [internship at Posit](./posts/Posit%20Internship%20Reflection/index.qmd)

## Personal Projects

**Marion Stokes Shiny Dashboard**
    
* The [dashboard](https://jules-dev.shinyapps.io/Marion-Stokes-Tapes-Dashboard/) is a place to explore television news data from the Marion Stokes tapes archive
* In collaboration with Daniel Fernandez, a history student at The New School working on his senior thesis

**Mega Tic Tac Toe**

* An [iOS app](https://github.com/juleswg23/MegaTicTacToe) to play tic tac toe inside of tic tac toe
* Here are the [rules](https://bejofo.com/ttt), but be careful I'm always up for a game 

**Connect Four**

* Socket-backed [Connect four](https://github.com/juleswg23/connect-four-live) full-stack application written in TypeScript
* Play in real time [here](https://ancient-chelsae-jules-personal-c110e413.koyeb.app/)
